package com.vk.admstorm.executors

import com.intellij.icons.AllIcons
import com.intellij.openapi.project.Project
import com.vk.admstorm.git.sync.files.RemoteFileManager
import com.vk.admstorm.notifications.AdmNotification
import javax.swing.Icon

class BuildersExecutor(project: Project, command: String) :
    BaseRunnableExecutor(Config(name = "Builders", command = command), project) {

    override fun onReady() {
        RemoteFileManager(project).updateAutogeneratedFilesThatChangedOrCreatedOnServer { stat ->
            if (stat.isEmpty()) {
                AdmNotification("No changes")
                    .withTitle("Autogenerated files updated")
                    .show()
                return@updateAutogeneratedFilesThatChangedOrCreatedOnServer
            }

            AdmNotification("Changed: ${stat.countChanged}, Added: ${stat.countAdded}, Deleted: ${stat.countDeleted}")
                .withTitle("Autogenerated files updated")
                .show()
        }
    }

    override fun icon(): Icon = AllIcons.Toolwindows.ToolWindowBuild
}
