package com.vk.admstorm.executors

import com.intellij.icons.AllIcons
import com.intellij.openapi.project.Project
import com.vk.admstorm.git.sync.files.RemoteFileManager

class BuildersExecutor(project: Project, private val command: String) : BaseRemoteExecutor(project, "Builders") {
    override fun layoutName() = "Builders"

    override fun tabName() = "Builders"

    override fun command() = command

    override fun icon() = AllIcons.Toolwindows.ToolWindowBuild

    override fun onFinish() {
        RemoteFileManager(project).doUpdateAutogeneratedFiles()
    }
}
