package com.vk.admstorm.executors

import com.intellij.icons.AllIcons
import com.intellij.openapi.project.Project
import com.vk.admstorm.git.sync.files.RemoteFileManager
import javax.swing.Icon

class BuildersExecutor(project: Project, command: String) :
    BaseRunnableExecutor(Config(tabName = "Builders", command = command), project) {

    override fun onFinish() {
        RemoteFileManager(project).doUpdateAutogeneratedFiles()
    }

    override fun icon(): Icon = AllIcons.Toolwindows.ToolWindowBuild
}
