package com.vk.admstorm.actions

import com.intellij.openapi.actionSystem.AnActionEvent
import com.vk.admstorm.git.sync.files.RemoteFileManager
import com.vk.admstorm.notifications.AdmNotification

class SyncAutogeneratedFilesAction : AdmActionBase() {
    override fun actionWithConnectionPerformed(e: AnActionEvent) {
        RemoteFileManager(e.project!!).updateAutogeneratedFilesThatChangedOrCreatedOnServer { stat ->
            if (stat.isEmpty()) {
                return@updateAutogeneratedFilesThatChangedOrCreatedOnServer
            }

            AdmNotification("Changed: ${stat.countChanged}, Added: ${stat.countAdded}, Deleted: ${stat.countDeleted}")
                .withTitle("Autogenerated files updated")
                .show()
        }
    }
}
